In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the CSV file
#file_path = './data/creatures_EDL.csv'
file_path = './data/heartbeat_EDL.csv'
df = pd.read_csv(file_path, sep='\t')
df.columns = ['CHANNEL', 'EVENT', 'CLIP NAME', 'START TIME', 'END TIME', 'DURATION', 'STATE']

In [71]:
df.head()

,CHANNEL,EVENT,CLIP NAME,START TIME,END TIME,DURATION,STATE
0,1,1,Nu Heartbeat.01_01-171.L,00:00:03:04,00:00:03:12,00:00:00:08,Unmuted
1,1,2,Nu Heartbeat.01_01-172.L,00:00:03:12,00:00:04:00,00:00:00:17,Unmuted
2,1,3,Nu Heartbeat.01_01-173.L,00:00:04:00,00:00:04:08,00:00:00:08,Unmuted
3,1,4,Nu Heartbeat.01_01-174.L,00:00:04:08,00:00:04:25,00:00:00:17,Unmuted
4,1,5,Nu Heartbeat.01_01-843.L,00:00:04:25,00:00:05:03,00:00:00:08,Unmuted

In [72]:
df.shape

(1171, 7)

In [73]:
df['DURATION'] = df['DURATION'].str.strip()
df['START TIME'] = df['START TIME'].str.strip()
df['END TIME'] = df['END TIME'].str.strip()

In [74]:
#clean data
df_cleaned = df[df['DURATION'] != "00:00:00:00"]

# Reindex the DataFrame
df_cleaned.reset_index(drop=True, inplace=True)

# Display the cleaned DataFrame
print(df_cleaned)

      CHANNEL  EVENT                       CLIP NAME   START TIME  \
0           1      1  Nu Heartbeat.01_01-171.L        00:00:03:04
1           1      2  Nu Heartbeat.01_01-172.L        00:00:03:12
2           1      3  Nu Heartbeat.01_01-173.L        00:00:04:00
3           1      4  Nu Heartbeat.01_01-174.L        00:00:04:08
4           1      5  Nu Heartbeat.01_01-843.L        00:00:04:25
...       ...    ...                             ...          ...
1157        1   1167  Nu Heartbeat.01_01-08.L         00:11:56:06
1158        1   1168  Nu Heartbeat.01_01-297.L        00:11:56:23
1159        1   1169  Nu Heartbeat.01_01-298.L        00:11:57:02
1160        1   1170  Nu Heartbeat.01_01-299.L        00:11:57:19
1161        1   1171  Nu Heartbeat.01_01-912.L        00:11:57:28

         END TIME     DURATION    STATE
0     00:00:03:12  00:00:00:08  Unmuted
1     00:00:04:00  00:00:00:17  Unmuted
2     00:00:04:08  00:00:00:08  Unmuted
3     00:00:04:25  00:00:00:17  Unmuted
4     00:00:05:03  00:00:00:08  Unmuted
...           ...          ...      ...
1157  00:11:56:23  00:00:00:17  Unmuted
1158  00:11:57:02  00:00:00:08  Unmuted
1159  00:11:57:19  00:00:00:17  Unmuted
1160  00:11:57:28  00:00:00:08  Unmuted
1161  00:11:58:14  00:00:00:16  Unmuted

[1162 rows x 7 columns]

In [75]:
df_cleaned.dtypes

CHANNEL        int64
EVENT          int64
CLIP NAME     object
START TIME    object
END TIME      object
DURATION      object
STATE         object
dtype: object

In [76]:
df_cleaned.head()

,CHANNEL,EVENT,CLIP NAME,START TIME,END TIME,DURATION,STATE
0,1,1,Nu Heartbeat.01_01-171.L,00:00:03:04,00:00:03:12,00:00:00:08,Unmuted
1,1,2,Nu Heartbeat.01_01-172.L,00:00:03:12,00:00:04:00,00:00:00:17,Unmuted
2,1,3,Nu Heartbeat.01_01-173.L,00:00:04:00,00:00:04:08,00:00:00:08,Unmuted
3,1,4,Nu Heartbeat.01_01-174.L,00:00:04:08,00:00:04:25,00:00:00:17,Unmuted
4,1,5,Nu Heartbeat.01_01-843.L,00:00:04:25,00:00:05:03,00:00:00:08,Unmuted

In [77]:
df_cleaned['START TIME'] = df_cleaned['START TIME'].astype(str)

def timecode_to_frames(timecode):
    try:
        hours, minutes, seconds, frames = map(int, timecode.split(':'))
        total_frames = ((hours * 3600) + (minutes * 60) + seconds) * 30 + frames
        return total_frames
    except ValueError:
        return None  # Return None for invalid timecodes

# Apply the function to the 'START TIME' column
df_cleaned['Frames'] = df_cleaned['START TIME'].apply(timecode_to_frames)
df_cleaned['Runtime'] = df_cleaned['DURATION'].apply(timecode_to_frames)
df_cleaned['Beats'] = df_cleaned['EVENT'] % 2
df_cleaned.head()

/var/folders/ww/rg8zlhq16mqg0kz1wk66r9b00000gn/T/ipykernel_8374/175183845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['START TIME'] = df_cleaned['START TIME'].astype(str)
/var/folders/ww/rg8zlhq16mqg0kz1wk66r9b00000gn/T/ipykernel_8374/175183845.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Frames'] = df_cleaned['START TIME'].apply(timecode_to_frames)
/var/folders/ww/rg8zlhq16mqg0kz1wk66r9b00000gn/T/ipykernel_8374/175183845.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Runtime'] = df_cleaned['DURATION'].apply(timecode_to_frames)
/var/folders/ww/rg8zlhq16mqg0kz1wk66r9b00000gn/T/ipykernel_8374/175183845.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Beats'] = df_cleaned['EVENT'] % 2

,CHANNEL,EVENT,CLIP NAME,START TIME,END TIME,DURATION,STATE,Frames,Runtime,Beats
0,1,1,Nu Heartbeat.01_01-171.L,00:00:03:04,00:00:03:12,00:00:00:08,Unmuted,94,8,1
1,1,2,Nu Heartbeat.01_01-172.L,00:00:03:12,00:00:04:00,00:00:00:17,Unmuted,102,17,0
2,1,3,Nu Heartbeat.01_01-173.L,00:00:04:00,00:00:04:08,00:00:00:08,Unmuted,120,8,1
3,1,4,Nu Heartbeat.01_01-174.L,00:00:04:08,00:00:04:25,00:00:00:17,Unmuted,128,17,0
4,1,5,Nu Heartbeat.01_01-843.L,00:00:04:25,00:00:05:03,00:00:00:08,Unmuted,145,8,1

In [78]:
# Convert 'Frames' to integer
df_cleaned['Frames'] = df_cleaned['Frames'].fillna(0)
df_cleaned['Frames'] = df_cleaned['Frames'].astype(int)

# Sort by 'Frames' column in ascending order and reset the index
df_cleaned = df_cleaned.sort_values(by='Frames').reset_index(drop=True)
df_cleaned.tail()

/var/folders/ww/rg8zlhq16mqg0kz1wk66r9b00000gn/T/ipykernel_8374/1150897096.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Frames'] = df_cleaned['Frames'].fillna(0)
/var/folders/ww/rg8zlhq16mqg0kz1wk66r9b00000gn/T/ipykernel_8374/1150897096.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Frames'] = df_cleaned['Frames'].astype(int)

,CHANNEL,EVENT,CLIP NAME,START TIME,END TIME,DURATION,STATE,Frames,Runtime,Beats
1157,1,1167,Nu Heartbeat.01_01-08.L,00:11:56:06,00:11:56:23,00:00:00:17,Unmuted,21486,17,1
1158,1,1168,Nu Heartbeat.01_01-297.L,00:11:56:23,00:11:57:02,00:00:00:08,Unmuted,21503,8,0
1159,1,1169,Nu Heartbeat.01_01-298.L,00:11:57:02,00:11:57:19,00:00:00:17,Unmuted,21512,17,1
1160,1,1170,Nu Heartbeat.01_01-299.L,00:11:57:19,00:11:57:28,00:00:00:08,Unmuted,21529,8,0
1161,1,1171,Nu Heartbeat.01_01-912.L,00:11:57:28,00:11:58:14,00:00:00:16,Unmuted,21538,16,1

In [79]:
# Save the new DataFrame as a CSV file
output_path = './data/heartbeat_01.csv'
df_cleaned.to_csv(output_path, index=False)